name: esp32 port

on: [push, workflow_dispatch]

jobs:
  build_esp32:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Init idf
      run: |
        git clone -b v4.0.2 --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        git checkout v4.2
        git submodule update --init --recursive
        ./install.sh
        source export.sh
        
    - name: make -C mpy-cross
      run: make -C mpy-cross

    - name: cd ports/esp32
      run: cd ports/esp32

    - name: make submodules
      run: make submodules

    - name: make BOARD=PYDRONE
      run: make BOARD=PYDRONE
