name: esp32 port

on: [push, workflow_dispatch]

jobs:
  build_esp32:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: install idf v4.4
      run: |
        git clone -b v4.4 --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh
        source export.sh

    - name: add esp-who
      run: |
        git clone -b idfv4.4 https://github.com/espressif/esp-who.git ./tmp
        cd tmp
        git submodule update --init --recursive
        cd ..
        mv tmp/components/* esp-idf/components/
        # cd esp-idf/components/
        # rm -rf esp32-camera
        
    - name: build
      run: |
        source ./esp-idf/export.sh
        cd ports/esp32
        # git submodule update --init --recursive
        make BOARD=PYDRONE

    - name: Get current date and time
      id: datetime
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

    - name: Upload Prerelease
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{steps.datetime.outputs.date}}
        name: v${{steps.datetime.outputs.date}}
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
        append_body: true
        files: |
          ports/esp32/build-PYDRONE/*.bin
