name: esp32 port

on: [push, workflow_dispatch]

jobs:
  build_esp32:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker run -i -v ./ports/esp32:/project -w /project espressif/idf:v4.4 bash -c "idf.py build"
