name: esp32 port

on: [push, workflow_dispatch]

jobs:
  build_esp32:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Init idf
      run: |
        git clone -b v4.0.2 --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        git checkout v4.2
        git submodule update --init --recursive
        ./install.sh
        source export.sh
        
    - name: build
      run: |
        make -C mpy-cross
        cd ports/esp32
        make submodules
        make BOARD=PYDRONE
