name: esp32 port

on: [push, workflow_dispatch]

jobs:
  build_esp32:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: install idf v4.4
      run: |
        git clone -b v4.4 --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh
        source export.sh

    - name: add esp-who
      run: |
        git clone -b idfv4.4 https://github.com/espressif/esp-who.git ./tmp
        mv tmp/components/* esp-idf/components/
        
    - name: build
      run: |
        source ./esp-idf/export.sh
        cd ports/esp32
        # git submodule update --init --recursive
        make BOARD=PYDRONE
