name: esp32 port

on: [push, workflow_dispatch]

jobs:
  build_esp32:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: install idf v4.4
      run: |
        git clone -b v4.0.2 --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        git checkout v4.4
        git submodule update --init --recursive
        ./install.sh
        source export.sh

    - name: add esp-who
      run: |
        git clone https://github.com/espressif/esp-who.git ./tmp
        mv tmp/components/* esp-idf/components/
        cd esp-idf/components
        rm -rf esp32_s3_eye_noglib
        rm -rf who_peripherals
        
    - name: build
      run: |
        source ./esp-idf/export.sh
        cd ports/esp32
        make submodules
        make BOARD=PYDRONE
