name: esp32 port

on: [push, workflow_dispatch]

jobs:
  build_esp32:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        git clone -b v4.0.2 --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        git checkout v4.2
        git submodule update --init --recursive
        ./install.sh
        source export.sh
        
        cd ../ports/esp32
        git submodule update --remote ../../lib/berkeley-db-1.xx
        make submodules
        make BOARD=PYDRONE
