name: esp32 port

on: [push, workflow_dispatch]

jobs:
  build_esp32:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker run -i -v .:/project -w /project espressif/idf:v4.4 bash -c "make -C mpy-cross && cd ports/esp32 && make submodules && make BOARD=GENERIC_SPIRAM"
